### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1

### ISSUE THREAD

**Issue by itxuye** [xmuSistone/android-vertical-slide-view#12]
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
    at android.support.v4.widget.ViewDragHelper.saveLastMotion(ViewDragHelper.java:848)
    at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1052)
    at com.jimei.xiaolumeimei.widget.doubleview.DragLayout.onInterceptTouchEvent(DragLayout.java:143)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1886)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2243)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1986)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2243)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1986)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2243)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1986)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2243)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1986)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2243)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1986)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2243)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1986)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2243)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1986)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2243)
    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1548)
    at android.app.Activity.dispatchTouchEvent(Activity.java:2509)
    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2069)
    at android.view.View.dispatchPointerEvent(View.java:7901)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4295)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4174)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3733)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3783)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3752)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3859)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3760)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3916)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3733)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3783)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3752)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3760)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3733)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5899)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5863)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5834)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5979)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
    at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5952)
    at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5998)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
    at android.view.Choreographer.doCallbacks(Choreographer.java:574)
    at android.view.Choreographer.doFrame(Choreographer.java:542)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5032)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by xmuSistone** [comment]
你改了DragLayout的touch拦截吧？

**Comment by xmuSistone** [comment]
DragLayout里面的dispatchTouchEvent最好不要改动了。DragLayout上游ParentView的touch传递策略可能有误，理论上来说，shouldInterceptTouchEvent是不会报异常的。

**Comment by itxuye** [comment]
@xmuSistone  没有改,代码原封不动的加上去的，部分手机出现了这个bug

**Comment by xmuSistone** [comment]
什么型号的手机呢？

**Comment by EmilyCYY** [comment]
您好，我也出现了这个问题。是在魅族note2上出现的，复现：我把scrollview改了之后放在第二个fragment中，然后在scrollview中进行放大的手势就会出现这个问题了。draglayout我是没有改动过的

**Comment by xmuSistone** [comment]
@EmilyCYY 你更新下DragLayout，提了新代码

**Comment by EmilyCYY** [comment]
@xmuSistone 非常感谢！
