### ISSUE TITLE
部分手机多点触摸时崩溃

### ISSUE THREAD

**Issue by kylin17** [xmuSistone/android-vertical-slide-view#30]
崩溃堆栈信息：
```
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
    at android.support.v4.widget.ViewDragHelper.saveLastMotion(ViewDragHelper.java:849)
    at android.support.v4.widget.ViewDragHelper.processTouchEvent(ViewDragHelper.java:1160)
    at com.stone.verticalslide.DragLayout.onInterceptTouchEvent(DraggableLayout.java:203)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2109)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at in.srain.cube.views.ptr.PtrFrameLayout.dispatchTouchEventSupper(PtrFrameLayout.java:255)
    at in.srain.cube.views.ptr.PtrFrameLayout.dispatchTouchEvent(PtrFrameLayout.java:331)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2405)
    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
    at android.app.Activity.dispatchTouchEvent(Activity.java:2835)
    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
    at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2366)
    at android.view.View.dispatchPointerEvent(View.java:9526)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4278)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4144)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3738)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3704)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3830)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3712)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3887)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3738)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3704)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3712)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5970)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5944)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5905)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6073)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootI
```

**Comment by xmuSistone** [comment]
try catch 一下就好了
